name: Deploy to GithubPages

on: pull_request
permissions:
  contents: write
jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Packages
        run: |
          npm ci

      - name: Build prod
        env:
          VITE_BACKEND_HOST: ${{ secrets.VITE_BACKEND_HOST }}
          VITE_BACKEND_PORT: ${{ secrets.VITE_BACKEND_PORT }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}

        run: |
          npm run build
          cp dist/index.html dist/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
